---
PLAINTEXT_VARIABLES:
    AGE_OF_HOLDS_TO_QUERY_HOURS: 144
    HOLDING_LOCATION_CODES: mal92,mal98,mal99,mag92,maf92,maf98,maf99,mas92,map92,map98
    LOG_LEVEL: debug
    NYPL_API_BASE_URL: https://qa-platform.nypl.org/api/v0.1
    NYPL_API_TOKEN_URL: https://isso.nypl.org/oauth/token
    PICKUP_LOCATION_CODES: mal
    SIERRA_DB_HOST: 127.0.0.1
    SIERRA_DB_NAME: sierra_local_item_status_listener
    SIERRA_DB_PORT: 5432
    SIERRA_DB_PASSWORD:
    SIERRA_DB_USER: postgres
ENCRYPTED_VARIABLES:
    NYPL_API_CLIENT_ID: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAGowaAYJKoZIhvcNAQcGoFswWQIBADBUBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDA/rHX5sfaQ0ZzgE8gIBEIAndEgQHjrdLyKw5S14fUTAkNgb0hSVQi47Qj7msRKF13jUQdF1+0BF
    NYPL_API_CLIENT_SECRET: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAIcwgYQGCSqGSIb3DQEHBqB3MHUCAQAwcAYJKoZIhvcNAQcBMB4GCWCGSAFlAwQBLjARBAxjiL15jRBbaa1wk6UCARCAQw54PgRwj5eDWrj1wnPY/K4bFmi+6ubPJvcvLqcB7gp19TUcPE0Hq8HdgF8AiB0SaU5xLtF4qO0NK1N35T/dziC8yFI=
    REDIS_HOST: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAJIwgY8GCSqGSIb3DQEHBqCBgTB/AgEAMHoGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM+gAMM+CpcNP0FaJpAgEQgE1PGwL4gr/VKZtxdLLSaA8edyu17FfWphtZpYI92wVkDktdVcARyL6wDWWYsnKUYXbYfxEwyTy1QVmxQu53KeV9WPRG1wxNjyqi4SYRuQ==
    REDIS_PORT: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAGIwYAYJKoZIhvcNAQcGoFMwUQIBADBMBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDP8sOXotlgOf91oFZQIBEIAfy2WpzXXtYRWtvZKpMuibq+08Y51ckipzZmYgheew0w==
...
