---
PLAINTEXT_VARIABLES:
    AWS_REGION: us-east-1
    HOLDING_LOCATION_CODES: mal92,mal98,mal99,mag92,maf92,maf98,maf99,mas92,map92,map98
    PICKUP_LOCATION_CODES: mal
    REDIS_HOST: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAJ0wgZoGCSqGSIb3DQEHBqCBjDCBiQIBADCBgwYJKoZIhvcNAQcBMB4GCWCGSAFlAwQBLjARBAwQxA1uZDGklTvdSyICARCAVrBkenY2iNUQLIexsmZq3CeNQr3n07M8HLTKvC8HMA5+cnCGg8GFPeOT3+nGznBY41VnlGDy20INC03QJGGEwdASSHcmvqFvKa/IgRN8KRh1SPcgonYa
    REDIS_PORT: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAGIwYAYJKoZIhvcNAQcGoFMwUQIBADBMBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDP8sOXotlgOf91oFZQIBEIAfy2WpzXXtYRWtvZKpMuibq+08Y51ckipzZmYgheew0w==
    SIERRA_DB_HOST: 127.0.0.1
    SIERRA_DB_PORT: 5432
    SIERRA_DB_NAME: sierra_local_item_status_listener
    SIERRA_DB_USER: postgres
    SIERRA_DB_PASSWORD:
    LOG_LEVEL: debug
...
