---
PLAINTEXT_VARIABLES:
    AGE_OF_HOLDS_TO_QUERY_HOURS: 72
    HOLDING_LOCATION_CODES: mal92,mal98,mal99,mag92,maf92,maf98,maf99,mas92,map92,map98,mab82,maf82,mag82,mai82,map82
    LOG_LEVEL: info
    NYPL_API_BASE_URL: https://platform.nypl.org/api/v0.1
    NYPL_API_TOKEN_URL: https://isso.nypl.org/oauth/token
    PICKUP_LOCATION_CODES: mal
    SIERRA_DB_NAME: iii
    SIERRA_DB_PORT: 1032
ENCRYPTED_VARIABLES:
    REDIS_HOST: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAI8wgYwGCSqGSIb3DQEHBqB/MH0CAQAweAYJKoZIhvcNAQcBMB4GCWCGSAFlAwQBLjARBAxhsYNNswsaQ9o1450CARCAS6dAzFcsCExs9vNaottVRC/MTn8ja/H9pLElEZlsw/CFF4xWjHxALKASAQeIZvWA8hlRkXTO2cFdGy4jVs+5C6s32cREpk69jlPTbA==
    REDIS_PORT: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAGIwYAYJKoZIhvcNAQcGoFMwUQIBADBMBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDP8sOXotlgOf91oFZQIBEIAfy2WpzXXtYRWtvZKpMuibq+08Y51ckipzZmYgheew0w==
    SIERRA_DB_HOST: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAGwwagYJKoZIhvcNAQcGoF0wWwIBADBWBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDOdjurfA/PQFeAgXmQIBEIApV18FKvG3ANBzIEvPGB5nCoRNRfolgDsUESU6UeDZc8ZNSbGRYjzeHIM=
    SIERRA_DB_USER: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAGkwZwYJKoZIhvcNAQcGoFowWAIBADBTBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDG09egmAS04a25zczAIBEIAmeD8bJZWJjiudXq5OIUQ9KnDb8WO03VItSTdj8ZRXlyBBv+76Cs0=
    SIERRA_DB_PASSWORD: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAG8wbQYJKoZIhvcNAQcGoGAwXgIBADBZBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDGUmp2AGtypf+QHJoAIBEIAsSfjzsrVfu50tioKGiYWEK6z/1fEFEAq88aXAGz63moGpFz0vMEnKdNecUQs=
    SIERRA_DB_USER: QECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAGkwZwYJKoZIhvcNAQcGoFowWAIBADBTBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDG09egmAS04a25zczAIBEIAmeD8bJZWJjiudXq5OIUQ9KnDb8WO03VItSTdj8ZRXlyBBv+76Cs0=
    NYPL_API_CLIENT_ID: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAGowaAYJKoZIhvcNAQcGoFswWQIBADBUBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDA/rHX5sfaQ0ZzgE8gIBEIAndEgQHjrdLyKw5S14fUTAkNgb0hSVQi47Qj7msRKF13jUQdF1+0BF
    NYPL_API_CLIENT_SECRET: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAIcwgYQGCSqGSIb3DQEHBqB3MHUCAQAwcAYJKoZIhvcNAQcBMB4GCWCGSAFlAwQBLjARBAxjiL15jRBbaa1wk6UCARCAQw54PgRwj5eDWrj1wnPY/K4bFmi+6ubPJvcvLqcB7gp19TUcPE0Hq8HdgF8AiB0SaU5xLtF4qO0NK1N35T/dziC8yFI=
...
