---
PLAINTEXT_VARIABLES:
    AWS_REGION: us-east-1
    HOLDING_LOCATION_CODES: mal92,mal98,mal99,mag92,maf92,maf98,maf99,mas92,map92,map98
    PICKUP_LOCATION_CODES: mal
    SIERRA_DB_PORT: 1032
    SIERRA_DB_NAME: iii
    LOG_LEVEL: info
ENCRYPTED_VARIABLES:
    REDIS_HOST: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAI0wgYoGCSqGSIb3DQEHBqB9MHsCAQAwdgYJKoZIhvcNAQcBMB4GCWCGSAFlAwQBLjARBAy8g/1UlpNY/hguJroCARCASUnosQugCL3UPxX0A6LzaCDvElgCbRjGpqRaDJZSTGhQXQSQYXbBwkLR9Gtc6EF7DjYMnJGilUSjFa0sdKLcUBTFUXvdMv+q+uM=
    REDIS_PORT: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAGIwYAYJKoZIhvcNAQcGoFMwUQIBADBMBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDP8sOXotlgOf91oFZQIBEIAfy2WpzXXtYRWtvZKpMuibq+08Y51ckipzZmYgheew0w==
    SIERRA_DB_HOST: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAGkwZwYJKoZIhvcNAQcGoFowWAIBADBTBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDCu20jxZpTC9cf9V8QIBEIAmt4TZJ7JuFQ1C845HxG8wAXzC7SFHkMNe4U6rKlD1twveXygfiQc=
    SIERRA_DB_USER: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAGcwZQYJKoZIhvcNAQcGoFgwVgIBADBRBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDCV82BNYC3MGUFAVfwIBEIAkpG132958p9Tz//Np8BENFyL5bk+NRkJXR+T+Z0/MKFxKTX4n
    SIERRA_DB_PASSWORD: AQECAHh7ea2tyZ6phZgT4B9BDKwguhlFtRC6hgt+7HbmeFsrsgAAAGkwZwYJKoZIhvcNAQcGoFowWAIBADBTBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDNOcPC3X2RjvquQnGgIBEIAm5iOucK+WlUlaV48b+F+85N3H30+HQPihI79g48aOpwHhI6YLjVY=
...
