name: Test and deploy
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r dev-requirements.txt
      - name: Run linter and test suite
        run: |
          make lint
          make test
  deploy-qa:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/qa'
    steps:
      - name: Package app
        run: provisioning/package.sh
      - name: Deploy app to QA
        uses: hashicorp/setup-terraform@v2
        run: |
          terraform -chdir=provisioning/qa init -input=false
          terraform -chdir=provisioning/qa apply -auto-approve -input=false

